<?php

/**
 * @file
 * Provides OAuth2 server functionality.
 */

/**
 * Implements hook_init().
 *
 * Nags the user about the missing library on OAuth2 admin pages.
 */
function oauth2_server_init() {
  $item = menu_get_item();
  if ($item['access'] && strpos($item['path'], 'admin/config/services/oauth2-servers') === 0) {
    $path = oauth2_server_get_library_path();
    // Check for the existence of one file from the library.
    if (!$path || !file_exists($path . '/src/OAuth2/Server.php')) {
      $message = t('The OAuth2 server library is required for the OAuth2 module to function.
        Download the library from <a href="https://github.com/bshaffer/oauth2-server-php" target="_blank">GitHub</a> and place it in <em>!path</em>.', array('!path' => $path));
      drupal_set_message($message, 'error');
    }
  }
}

/**
 * Implements hook_libraries_info().
 */
function oauth2_server_libraries_info() {
  $libraries = array();
  $libraries['oauth2-server-php'] = array(
    'name' => 'OAuth2 Server',
    'vendor url' => 'https://github.com/bshaffer/oauth2-server-php',
  );
  return $libraries;
}

/**
 * Returns the filesystem path to the oauth2-server-php library.
 */
function oauth2_server_get_library_path() {
  $path = 'sites/all/libraries/oauth2-server-php';
  // If installed, use the Libraries API to locate the library.
  if (module_exists('libraries')) {
    module_load_include('module', 'libraries');
    $path = libraries_get_path('oauth2-server-php');
  }

  return $path;
}

/**
 * Implements hook_menu().
 */
function oauth2_server_menu() {
  $items = array();
  $items['oauth2/authorize'] = array(
    'page callback' => 'oauth2_server_authorize',
    'access arguments' => array('access content'),
  );
  $items['oauth2/token'] = array(
    'page callback' => 'oauth2_server_token',
    'access arguments' => array('access content'),
  );
  $items['oauth2/verify_token'] = array(
    'page callback' => 'oauth2_server_verify_token',
    'access arguments' => array('access content'),
  );

  return $items;
}

/**
 * Implements hook_permission().
 */
function oauth2_server_permission() {
  return array(
    'administer oauth2 server' => array(
      'title' => t('Administer OAuth2 Server'),
      'description' => t('Manage servers, scopes, and clients.'),
      'restrict access' => TRUE,
    ),
  );
}

/**
 * Implements hook_services_authentication().
 */
function oauth2_server_services_authentication_info() {
  return array(
    'file' => 'includes/oauth2_server.services_auth.inc',
    'title' => t('OAuth2 authentication'),
    'description' => t('An open protocol to allow secure API authorization'),
    'security_settings' => 'oauth2_server_services_security_settings',
    'default_security_settings' => 'oauth2_server_services_default_security_settings',
    'authenticate_call' => 'oauth2_server_services_authenticate_call',
    'controller_settings' => 'oauth2_server_services_controller_settings',
  );
}

/**
 * Implements hook_entity_info().
 */
function oauth2_server_entity_info() {
  $items = array();
  $items['oauth2_server'] = array(
    'label' => t('OAuth2 Server'),
    'controller class' => 'OAuth2ServerEntityController',
    'entity class' => 'OAuth2Server',
    'base table' => 'oauth2_server',
    'fieldable' => TRUE,
    'entity keys' => array(
      'id' => 'server_id',
      'label' => 'label',
      'name' => 'name',
    ),
    'exportable' => TRUE,
    'export' => array(
      'default hook' => 'default_oauth2_server',
    ),
    'module' => 'oauth2_server',
    'access callback' => 'oauth2_server_access',
    'metadata controller class' => 'EntityDefaultMetadataController',
    'views controller class' => 'EntityDefaultViewsController',
    'admin ui' => array(
      'path' => 'admin/config/services/oauth2-servers',
      'file' => 'includes/oauth2_server.server_admin.inc',
      'controller class' => 'OAuth2ServerUIController',
    ),
  );
  $items['oauth2_server_scope'] = array(
    'label' => t('OAuth2 Server - Scope'),
    'controller class' => 'EntityAPIController',
    'entity class' => 'OAuth2ServerScope',
    'base table' => 'oauth2_server_scope',
    'fieldable' => TRUE,
    'entity keys' => array(
      'id' => 'scope_id',
      'label' => 'label',
    ),
    'module' => 'oauth2_server',
    'access callback' => 'oauth2_server_scope_access',
    'metadata controller class' => 'OAuth2ServerScopeMetadataController',
    'views controller class' => 'EntityDefaultViewsController',
    'admin ui' => array(
      'path' => 'admin/config/services/oauth2-servers/manage/%/scopes',
      'file' => 'includes/oauth2_server.scope_admin.inc',
      'controller class' => 'OAuth2ServerScopeUIController',
    ),
  );
  $items['oauth2_server_client'] = array(
    'label' => t('OAuth2 Server - Client'),
    'controller class' => 'EntityAPIController',
    'entity class' => 'OAuth2ServerClient',
    'base table' => 'oauth2_server_client',
    'fieldable' => TRUE,
    'entity keys' => array(
      'id' => 'client_id',
      'label' => 'label',
    ),
    'module' => 'oauth2_server',
    'access callback' => 'oauth2_server_client_access',
    'metadata controller class' => 'OAuth2ServerClientMetadataController',
    'views controller class' => 'EntityDefaultViewsController',
    'admin ui' => array(
      'path' => 'admin/config/services/oauth2-servers/manage/%/clients',
      'file' => 'includes/oauth2_server.client_admin.inc',
      'controller class' => 'OAuth2ServerClientUIController',
    ),
  );
  $items['oauth2_server_token'] = array(
    'label' => t('OAuth2 Server - Token'),
    'controller class' => 'EntityAPIController',
    'entity class' => 'OAuth2ServerToken',
    'base table' => 'oauth2_server_token',
    'fieldable' => TRUE,
    'entity keys' => array(
      'id' => 'token_id',
      'bundle' => 'type',
    ),
    'bundles' => array(
      'access' => array(
        'label' => t('Access token'),
      ),
      'refresh' => array(
        'label' => t('Refresh token')
      ),
    ),
    'module' => 'oauth2_server',
    'metadata controller class' => 'OAuth2ServerTokenMetadataController',
    'views controller class' => 'EntityDefaultViewsController',
  );
  $items['oauth2_server_authorization_code'] = array(
    'label' => t('OAuth2 Server - Authorization code'),
    'controller class' => 'EntityAPIController',
    'entity class' => 'OAuth2ServerAuthorizationCode',
    'base table' => 'oauth2_server_authorization_code',
    'fieldable' => TRUE,
    'entity keys' => array(
      'id' => 'code_id',
    ),
    'module' => 'oauth2_server',
    'metadata controller class' => 'OAuth2ServerAuthorizationCodeMetadataController',
    // Authorization codes don't need Views integration.
    'views controller class' => FALSE,
  );

  return $items;
}

/**
 * Implements hook_flush_caches().
 */
function oauth2_server_flush_caches() {
  $field = field_info_field('scopes');
  // Create the scopes reference field if it's missing.
  if (!$field) {
    $field = array(
      'field_name' => 'scopes',
      'cardinality' => FIELD_CARDINALITY_UNLIMITED,
      'translatable' => FALSE,
      'settings' => array(
        'target_type' => 'oauth2_server_scope',
      ),
      'module' => 'entityreference',
      'type' => 'entityreference',
    );
    field_create_field($field);
  }

  // Go over all bundles that should have an instance of the scopes field,
  // and create the instance where missing.
  $needed_instances = array(
    'oauth2_server_token' => array('access', 'refresh'),
    'oauth2_server_authorization_code' => array('oauth2_server_authorization_code'),
  );
  foreach ($needed_instances as $entity_type => $bundles) {
    $existing = array();
    if (!empty($field['bundles'][$entity_type])) {
      $existing = $field['bundles'][$entity_type];
    }
    $diff = array_diff($bundles, $existing);
    foreach ($diff as $new_bundle) {
      $instance = array(
        'label' => 'Scopes',
        'field_name' => 'scopes',
        'entity_type' => $entity_type,
        'bundle' => $new_bundle,
      );
      field_create_instance($instance);
    }
  }
}

/**
 * Access control for oauth2_server entities.
 *
 * @param $op
 *   The operation being performed. One of 'view', 'update', 'create' or
 *   'delete'.
 * @param $entity
 *   Optionally an entity to check access for. If no entity is given, it will be
 *   determined whether access is allowed for all entities of the given type.
 * @param $account
 *   The user to check for. Leave it to NULL to check for the global user.
 * @param $entity_type
 *   The entity type of the entity to check for.
 *
 * @see entity_access()
 */
function oauth2_server_access($op, $entity, $account, $entity_type) {
  return user_access('administer oauth2 server', $account);
}

/**
 * Loads a single server entity.
 *
 * @param $name
 *   The server machine name.
 *
 * @return
 *   The server entity, or FALSE.
 */
function oauth2_server_load($name) {
  return entity_load_single('oauth2_server', $name);
}

/**
 * Loads multiple server entities.
 *
 * @param $names
 *   An array of server machine names.
 *
 * @return
 *   An array of server entities indexed by their ids.
 */
function oauth2_server_load_multiple($names) {
  return entity_load_multiple_by_name('oauth2_server', $names);
}

/**
 * Access control for oauth2_server_scope entities.
 *
 * @param $op
 *   The operation being performed. One of 'view', 'update', 'create' or
 *   'delete'.
 * @param $entity
 *   Optionally an entity to check access for. If no entity is given, it will be
 *   determined whether access is allowed for all entities of the given type.
 * @param $account
 *   The user to check for. Leave it to NULL to check for the global user.
 * @param $entity_type
 *   The entity type of the entity to check for.
 *
 * @see entity_access()
 */
function oauth2_server_scope_access($op, $entity, $account, $entity_type) {
  if ($entity) {
    // Scope access depends on server access.
    $server = oauth2_server_load($entity->server);
    return oauth2_server_access($op, $server, $account, 'oauth2_server');
  }

  return user_access('administer oauth2 server', $account);
}

/**
 * Loads a single scope entity.
 *
 * @param $server
 *   The server machine name.
 * @param $name
 *   The scope machine name.
 *
 * @return
 *   The scope entity, or FALSE.
 */
function oauth2_server_scope_load($server, $name) {
  $conditions = array(
    'server' => $server,
    'name' => $name,
  );
  $scopes = entity_load('oauth2_server_scope', FALSE, $conditions);
  return reset($scopes);
}

/**
 * Loads multiple scope entities.
 *
 * @param $server
 *   The server machine name.
 * @param $names
 *   An array of scope machine names.
 *
 * @return
 *   An array of scope entities indexed by their ids.
 */
function oauth2_server_scope_load_multiple($server, $names) {
  $conditions = array(
    'server' => $server,
    'name' => $names,
  );
  return entity_load('oauth2_server_scope', FALSE, $conditions);
}

/**
 * Access control for oauth2_server_client entities.
 *
 * @param $op
 *   The operation being performed. One of 'view', 'update', 'create' or
 *   'delete'.
 * @param $entity
 *   Optionally an entity to check access for. If no entity is given, it will be
 *   determined whether access is allowed for all entities of the given type.
 * @param $account
 *   The user to check for. Leave it to NULL to check for the global user.
 * @param $entity_type
 *   The entity type of the entity to check for.
 *
 * @see entity_access()
 */
function oauth2_server_client_access($op, $entity, $account, $entity_type) {
  return user_access('administer oauth2 server', $account);
}

/**
 * Loads a single client entity.
 *
 * @param $client_key
 *   The client key.
 *
 * @return
 *   The client entity, or FALSE.
 */
function oauth2_server_client_load($client_key) {
  $clients = entity_load('oauth2_server_client', FALSE, array('client_key' => $client_key));
  return reset($clients);
}

/**
 * Loads multiple client entities.
 *
 * @param $client_keys
 *   An array of client keys.
 *
 * @return
 *   An array of client entities indexed by their ids.
 */
function oauth2_server_client_load_multiple($client_keys) {
  return entity_load('oauth2_server_client', FALSE, array('client_key' => $client_keys));
}

/**
 * Loads a single token entity.
 *
 * @param $token
 *   The token.
 *
 * @return
 *   The token entity, or FALSE.
 */
function oauth2_server_token_load($token) {
  $tokens = entity_load('oauth2_server_token', FALSE, array('token' => $token));
  return reset($tokens);
}

/**
 * Loads multiple token entities.
 *
 * @param $tokens
 *   An array of tokens.
 *
 * @return
 *   An array of token entities indexed by their ids.
 */
function oauth2_server_token_load_multiple($tokens) {
  return entity_load('oauth2_server_token', FALSE, array('token' => $tokens));
}

/**
 * Loads a single authorization code entity.
 *
 * @param $code
 *   The code.
 *
 * @return
 *   The authorization code entity, or FALSE.
 */
function oauth2_server_authorization_code_load($code) {
  $codes = entity_load('oauth2_server_authorization_code', FALSE, array('code' => $code));
  return reset($codes);
}

/**
 * Loads multiple authorization code entities.
 *
 * @param $codes
 *   An array of codes.
 *
 * @return
 *   An array of authorization code entities indexed by their ids.
 */
function oauth2_server_authorization_code_load_multiple($codes) {
  return entity_load('oauth2_server_authorization_code', FALSE, array('codes' => $codes));
}

/**
 * Entity Metadata getter callback: Returns the matching id for a computed
 * field.
 */
function oauth2_server_get_properties($entity, array $options, $name) {
  switch ($name) {
    case 'client':
      return $entity->client_id;
    case 'user':
      return $entity->uid;
  }
}

/**
 * Entity Metadata setter callback: Sets the matching id for a computed
 * field.
 */
function oauth2_server_set_properties($entity, $name, $value) {
  switch ($name) {
    case 'client':
      $entity->client_id = $value;
      break;
    case 'user':
      $entity->uid = $value;
      break;
  }
}

/**
 * Registers the OAuth2 autoloader to allow the library classes to be used.
 */
function oauth2_server_register_autoloader() {
  static $done = FALSE;

  if (!$done) {
    $path = oauth2_server_get_library_path();
    require_once $path . '/src/OAuth2/Autoloader.php';
    OAuth2_Autoloader::register();
    $done = TRUE;
  }
}

/**
 * Initializes and returns an OAuth2 server.
 *
 * @param $server
 *   The server entity to use for supplying settings to the server, and
 *   initializing the scope. NULL only when we expect the validation to
 *   fail due to an incomplete request.
 *
 * @return
 *   An instance of OAuth2_Server.
 */
function oauth2_server_start($server = NULL) {
  oauth2_server_register_autoloader();
  if ($server) {
    $storage = new OAuth2_Storage_Drupal();
    $oauth2_server = new OAuth2_Server($storage, $server->settings);
    // Initialize the scope util.
    $scope_util = new OAuth2_Scope_Drupal($server);
    $oauth2_server->setScopeUtil($scope_util);
    // Initialize the grant types.
    $grant_types = oauth2_server_grant_types();
    foreach (array_filter($server->settings['grant_types']) as $grant_type_name) {
      $grant_type = new $grant_types[$grant_type_name]['class']($storage, $server->settings);
      $oauth2_server->addGrantType($grant_type);
    }
  }
  else {
    $storage = new OAuth2_Storage_Drupal();
    $oauth2_server = new OAuth2_Server($storage);
  }

  return $oauth2_server;
}

/**
 * Page callback: Authenticates the user and redirect back to the client
 * with an authorization code.
 */
function oauth2_server_authorize() {
  global $user;

  // The user is not logged in. Redirect to login.
  if (!user_is_logged_in()) {
    // Save the parameters in session so that they can be fetched later.
    $parameters = drupal_get_query_parameters();
    $_SESSION['oauth2_server_authorize'] = $parameters;

    $query = array(
      'destination' => 'oauth2/authorize',
    );
    drupal_goto('user/login', array('query' => $query));
  }
  // Retrieve the parameters from session. Put them in $_GET so that
  // they are accessible by OAuth2_Request.
  if (!empty($_SESSION['oauth2_server_authorize'])) {
    $_GET += $_SESSION['oauth2_server_authorize'];
    unset($_SESSION['oauth2_server_authorize']);
  }

  $client_id = isset($_GET['client_id']) ? $_GET['client_id'] : 0;
  $server = NULL;
  // Get the client and use it to load the server and initialize the server.
  if ($client_id) {
    $client = oauth2_server_client_load($client_id);
    if ($client) {
      $server = oauth2_server_load($client->server);
    }
  }

  // Initialize the server.
  $oauth2_server = oauth2_server_start($server);
  $request = OAuth2_Request::createFromGlobals();

  // Automatic authorization is enabled for this client. Finish authorization.
  // handleAuthorizeRequest() will call validateAuthorizeRequest().
  if ($client->automatic_authorization) {
    $response = $oauth2_server->handleAuthorizeRequest($request, TRUE, $user->name);
    return oauth2_server_send_response($response);
  }
  else {
    // Validate the request.
    if (!$oauth2_server->validateAuthorizeRequest($request)) {
      return oauth2_server_send_response($oauth2_server->getResponse());
    }

    // Validation passed, show the authorize form.
    return drupal_get_form('oauth2_server_authorize_form', $client, $server);
  }
}

/**
 * Form callback: Returns the authorize form.
 *
 * @todo Implement scope selection.
 */
function oauth2_server_authorize_form($form, &$form_state, $client, $server) {
  drupal_set_title(t('Authorize @client to use your account?', array('@client' => $client->label)));

  // This application will be able to:
  $cancel_url = '';
  $form['authorize'] = array(
    '#type' => 'submit',
    '#value' => t('Yes, I authorize this request.'),
    '#suffix' => l(t('Cancel'), $cancel_url),
  );

  return $form;
}

/**
 * Submit callback for oauth2_server_authorize_form.
 *
 * Completes authentication and redirects back to the client.
 */
function oauth2_server_authorize_form_submit($form, &$form_state) {
  global $user;

  $server = $form_state['build_info']['args'][1];
  // Finish the authorization request.
  $oauth2_server = oauth2_server_start($server);
  $response = $oauth2_server->handleAuthorizeRequest(OAuth2_Request::createFromGlobals(), TRUE, $user->name);
  return oauth2_server_send_response($response);
}

/**
 * Page callback: exchanges an authorization code for an access token.
 */
function oauth2_server_token() {
  $client_id = isset($_POST['client_id']) ? $_POST['client_id'] : 0;
  $server = NULL;
  // Get the client and use it to load the server and initialize the server.
  if ($client_id) {
    $client = oauth2_server_client_load($client_id);
    if ($client) {
      $server = oauth2_server_load($client->server);
    }
  }

  // Initialize the server.
  $oauth2_server = oauth2_server_start($server);
  $response = $oauth2_server->handleGrantRequest(OAuth2_Request::createFromGlobals());
  return oauth2_server_send_response($response);
}

/**
 * Page callback: verifies the provided token for the provided client_id.
 */
function oauth2_server_verify_token($token) {
  $data = array(
    'verified' => FALSE,
    'scope' => '',
  );
  // If one of the parameters is missing, we can stop here.
  if (empty($token) || empty($_GET['client_id'])) {
    return drupal_json_output($data);
  }

  $token = oauth2_server_token_load($token);
  $client = oauth2_server_client_load($_GET['client_id']);
  // The token exists, hasn't expired, and belongs to the provided client.
  if ($token && $client && $token->expires > time() && $token->client_id == $client->client_id) {
    $token_wrapper = entity_metadata_wrapper('oauth2_server_token', $token);
    $scopes = array();
    foreach ($token_wrapper->scopes as $scope_wrapper) {
      $scopes[] = $scope_wrapper->name->value();
    }

    $data = array(
      'verified' => TRUE,
      'scope' => implode(' ', $scopes),
    );
  }

  return drupal_json_output($data);
}

/**
 * Verifies access to the passed server.
 *
 * @param $server_name
 *   The name of the server for which access should be verified.
 * @param $scope
 *   An optional string of space-separated scopes to check.
 *
 * @return
 *   No return value. If the access check fails, execution is aborted and an
 *   error response is sent to the user.
 */
function oauth2_server_verify_access($server_name, $scope = NULL) {
  $server = oauth2_server_load($server_name);
  $oauth2_server = oauth2_server_start($server);
  $token = $oauth2_server->getAccessTokenData(OAuth2_Request::createFromGlobals());
  // If there's no token, that means validation failed. Stop here.
  if (!$token) {
    return oauth2_server_send_response($oauth2_server->getResponse());
  }

  // Make sure that the token we have matches our server.
  if ($token['server'] != $server->name) {
    $error = 'The access token provided is invalid';
    $response = new OAuth2_Response_AuthenticationError(401, 'invalid_grant', $error, 'bearer', 'Service', $scope);
    return oauth2_server_send_response($response);
  }
}

/**
 * Sets the appropriate headers and outputs the response.
 */
function oauth2_server_send_response(OAuth2_Response $response) {
  $status = $response->getStatusCode() . ' ' . $response->getStatusText();
  drupal_add_http_header('Status', $status);
  drupal_add_http_header('Content-Type', 'application/json');
  foreach ($response->getHttpHeaders() as $name => $header) {
    drupal_add_http_header($name, $header);
  }

  echo $response->getResponseBody('json');
  drupal_exit();
}

/**
 * Returns an array of supported grant types and related data.
 */
function oauth2_server_grant_types() {
  $grant_types = array(
    'authorization_code' => array(
      'name' => t('Authorization code'),
      'class' => 'OAuth2_GrantType_AuthorizationCode',
    ),
    'client_credentials' => array(
      'name' => t('Client credentials'),
      'class' => 'OAuth2_GrantType_ClientCredentials',
    ),
    //'urn:ietf:params:oauth:grant-type:jwt-bearer' => array(
    //  'name' => t('JWT bearer'),
    //  'class' => 'OAuth2_GrantType_JWTBearer',
    //),
    'refresh_token' => array(
      'name' => t('Refresh token'),
      'class' => 'OAuth2_GrantType_RefreshToken',
      'settings callback' => 'oauth2_server_refresh_token_settings',
      'default settings' => array(
        'always_issue_new_refresh_token' => FALSE,
      ),
    ),
    'password' => array(
      'name' => t('User credentials'),
      'class' => 'OAuth2_GrantType_UserCredentials',
    ),
  );

  return $grant_types;
}

/**
 * Provides a settings form for the refresh_token grant type.
 */
function oauth2_server_refresh_token_settings($config, $dom_id) {
  $form = array();
  $form['always_issue_new_refresh_token'] = array(
    '#type' => 'checkbox',
    '#title' => t('Always issue a new refresh token after the existing one has been used'),
    '#default_value' => $config['always_issue_new_refresh_token'],
    '#states' => array(
      'visible' => array(
        '#' . $dom_id => array('checked' => TRUE),
      ),
    ),
  );
  return $form;
}
